export const superadmintabledata = [
    {
      adminId: 'CA00003',
      adminName: 'musthaq',
      adminType: 'Goverment',
      organization: 'Dubai Water Authority',
      contactPerson: 'Musthaq',
      contactNumber: '+971-879494993',
      email: 'musthaq@gmail.com',
      currency: 'AED',
      plotno: 'Burj Khalifa Blvd, Downtown',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
        {
      adminId: 'CA00004',
      adminName: 'mohammed',
      adminType: 'Government',
      organization: 'Dubai Municipality',
      contactPerson: 'Wasim Akram',
      contactNumber: '+971-989856738',
      email: 'mohammed@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    },
    {
      adminId: 'CA00017',
      adminName: 'abbas',
      adminType: 'Government',
      organization: 'Emirates Group',
      contactPerson: 'Abbas',
      contactNumber: '+971-8765434562',
      email: 'abbas@gmail.com',
      currency: 'AED',
      plotno: '123,Airport Street',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
    }

]

export const devicetabledata = [
  {   
    deviceId: '7634735985712',
    deviceName: 'Air Sensor',
    customerAdminName : 'musthaq',
    sensorType: 'Air',
    deviceMake: 'Raspberry',
    deviceModel: 'pico-324',
    status: 'Assigned'
  }
]