export const deviceTableData = [
    {
      deviceId: '9876543211234',
      deviceName: 'Watertest',
      customerAdminName: 'fahed',
      sensorType: 'Water',
      deviceMake: 'Rasperry',
      deviceModel: 'Pico-5',
      status: 'Assigned',
    },
    {
      deviceId: '8546513216546',
      deviceName: 'Water-demo2',
      customerAdminName: 'musthaq',
      sensorType: 'Water',
      deviceMake: 'Raspberry',
      deviceModel: 'Pico-5',
      status: 'Assigned',
    },
    {
      deviceId: '9856123216464',
      deviceName: 'Water-demo 9',
      customerAdminName: 'fahed',
      sensorType: 'Water',
      deviceMake: 'Raspberry',
      deviceModel: 'Pico-5',
      status: 'Assigned',
    },
    {
      deviceId: '9856123216546',
      deviceName: 'Water-demo 10',
      customerAdminName: 'musthaq',
      sensorType: 'Water',
      deviceMake: 'Raspberry',
      deviceModel: 'Pico-5',
      status: 'Assigned',
    },
    {
      deviceId: '9856123216546',
      deviceName: 'Water-demo 11',
      customerAdminName: 'fahed',
      sensorType: 'Water',
      deviceMake: 'Raspberry',
      deviceModel: 'Pico-5',
      status: 'Assigned',
    },
    {
      deviceId: '9856123216946',
      deviceName: 'Water-demo 12',
      customerAdminName: 'musthaq',
      sensorType: 'Water',
      deviceMake: 'Raspberry',
      deviceModel: 'Pico-5',
      status: 'Assigned',
    },
  ]
